version: "3"
services:
    spring-server:
        build: .
        ports:
          - 8080:8080
        depends_on:
          - mysqldb
        environment:
#            MYSQL_HOST: mysqldb
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
    mysqldb:
        image: "mysql:latest"
        ports:
          - 3307:3306
        environment:
           MYSQL_ROOT_PASSWORD: 123456
           MYSQL_DATABASE: mrMotorMasterDB