version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mrMotorMasterDB
    ports:
      - 3307:3306
    networks:
      - springdata

  app:
    image: imagemrmotormaster
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mrMotorMasterDB?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    ports:
      - 9090:8080
    depends_on:
      - db
    networks:
      - springdata

networks:
  springdata: